In [1]:
import numpy
numpy.random.seed(1337)
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [2]:
dataset=loadtxt('dataml.csv', delimiter=',')

In [3]:
print(dataset)

[[67. 90. 89. 56. 67.  1.]
 [67. 78. 76. 67. 88.  1.]
 [45. 32. 27. 45. 54.  0.]
 [87. 72. 85. 92. 96.  1.]
 [12. 43. 23. 32. 54.  0.]
 [54. 58. 65. 86. 63.  1.]
 [80. 78. 71. 65. 81.  1.]
 [32. 18. 39. 29. 42.  0.]
 [84. 89. 91. 70. 91.  1.]
 [29. 30. 38. 28. 18.  0.]]


In [4]:
x=dataset[:,0:5]
y=dataset[:,5]

In [5]:
model=Sequential()
model.add(Dense(512, input_dim=5,activation='sigmoid'))
model.add(Dense(512,activation='sigmoid'))
model.add(Dense(512,activation='sigmoid'))
model.add(Dense(1,activation='softmax'))

In [6]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [7]:
model.fit(x, y, epochs=150, batch_size=10)

Epoch 1/150
10/10 [==============================] - 4s 439ms/step - loss: 6.1333 - accuracy: 0.6000
Epoch 2/150
10/10 [==============================] - 0s 4ms/step - loss: 6.1333 - accuracy: 0.6000
Epoch 3/150
10/10 [==============================] - 0s 6ms/step - loss: 6.1333 - accuracy: 0.6000
Epoch 4/150
10/10 [==============================] - 0s 4ms/step - loss: 6.1333 - accuracy: 0.6000
Epoch 5/150
10/10 [==============================] - 0s 10ms/step - loss: 6.1333 - accuracy: 0.6000
Epoch 6/150
10/10 [==============================] - 0s 13ms/step - loss: 6.1333 - accuracy: 0.6000
Epoch 7/150
10/10 [==============================] - 0s 9ms/step - loss: 6.1333 - accuracy: 0.6000
Epoch 8/150
10/10 [==============================] - 0s 12ms/step - loss: 6.1333 - accuracy: 0.6000
Epoch 9/150
10/10 [==============================] - 0s 15ms/step - loss: 6.1333 - accuracy: 0.6000
Epoch 10/150
10/10 [==============================] - 0s 9ms/step - loss: 6.1333 - accuracy: 0.6000
Epo

In [8]:
_, accuracy = model.evaluate(x, y)
print('Accuracy: %.2f' % (accuracy*100))

10/10 [==============================] - 0s 10ms/step
Accuracy: 60.00
